/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <opencv2/opencv.hpp>

/* Header for class com_appdimension_pruebaopencv_NativeClass */

using namespace cv;

#ifndef _Included_com_appdimension_pruebaopencv_NativeClass
#define _Included_com_appdimension_pruebaopencv_NativeClass
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_appdimension_pruebaopencv_NativeClass
 * Method:    getMessageFromJNI
 * Signature: ()Ljava/lang/String;
 */

 void detect(Mat& frame);
  void detectXML(Mat& frame, String pathFrontalFace, String pathEyes);

JNIEXPORT jstring JNICALL Java_com_appdimension_pruebaopencv_NativeClass_getMessageFromJNI
  (JNIEnv *, jclass);

/*
 * Class:     com_appdimension_pruebaopencv_NativeClass
 * Method:    faceDetection
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT void JNICALL Java_com_appdimension_pruebaopencv_NativeClass_faceDetection
  (JNIEnv *, jclass, jlong);

JNIEXPORT void JNICALL Java_com_appdimension_pruebaopencv_NativeClass_faceDetectionXML
  (JNIEnv *, jclass, jlong, jstring, jstring);

void GetJStringContent(JNIEnv *AEnv, jstring AStr, std::string &ARes);

JNIEXPORT void JNICALL Java_com_appdimension_pruebaopencv_NativeClass_humanDetectionXML
  (JNIEnv *, jclass, jlong, jstring);

void detectHumanXML(Mat& frame, String pathHuman);

#ifdef __cplusplus
}
#endif
#endif
